# Generated by Django 5.0.6 on 2024-05-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('generos', models.ManyToManyField(to='Integrantes.generomusical')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('instrumento', models.CharField(max_length=100)),
                ('generos', models.ManyToManyField(to='Integrantes.generomusical')),
            ],
        ),
        migrations.CreateModel(
            name='Pertenece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_unido', models.DateField(auto_now_add=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Integrantes.banda')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Integrantes.musico')),
            ],
        ),
        migrations.AddField(
            model_name='banda',
            name='integrantes',
            field=models.ManyToManyField(through='Integrantes.Pertenece', to='Integrantes.musico'),
        ),
        migrations.CreateModel(
            name='SolicitudUnirseBanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Integrantes.banda')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Integrantes.musico')),
            ],
        ),
    ]
