# Generated by Django 5.0.6 on 2024-05-13 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Integrantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='integrantes',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='generos',
        ),
        migrations.AddField(
            model_name='banda',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Integrantes.generomusical'),
        ),
        migrations.AddField(
            model_name='musico',
            name='genero_primario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musico_genero_primario', to='Integrantes.generomusical'),
        ),
        migrations.AddField(
            model_name='musico',
            name='genero_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musico_genero_secundario', to='Integrantes.generomusical'),
        ),
    ]
