# Generated by Django 5.0.6 on 2024-05-29 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Integrantes', '0003_alter_banda_nombre_alter_generomusical_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='genero',
        ),
        migrations.AddField(
            model_name='banda',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='banda',
            name='generos',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='banda',
            name='instrumentos_buscados',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AlterField(
            model_name='banda',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
